export namespace Ad {
  export enum Type {
    DEPRECATED_AD = 'DEPRECATED_AD',
    IMAGE_AD = 'IMAGE_AD',
    PRODUCT_AD = 'PRODUCT_AD',
    TEMPLATE_AD = 'TEMPLATE_AD',
    TEXT_AD = 'TEXT_AD',
    THIRD_PARTY_REDIRECT_AD = 'THIRD_PARTY_REDIRECT_AD',
    DYNAMIC_SEARCH_AD = 'DYNAMIC_SEARCH_AD',
    CALL_ONLY_AD = 'CALL_ONLY_AD',
    EXPANDED_TEXT_AD = 'EXPANDED_TEXT_AD',
    RESPONSIVE_DISPLAY_AD = 'RESPONSIVE_DISPLAY_AD',
    SHOWCASE_AD = 'SHOWCASE_AD',
    GOAL_OPTIMIZED_SHOPPING_AD = 'GOAL_OPTIMIZED_SHOPPING_AD',
    EXPANDED_DYNAMIC_SEARCH_AD = 'EXPANDED_DYNAMIC_SEARCH_AD',
    GMAIL_AD = 'GMAIL_AD',
    RESPONSIVE_SEARCH_AD = 'RESPONSIVE_SEARCH_AD',
    MULTI_ASSET_RESPONSIVE_DISPLAY_AD = 'MULTI_ASSET_RESPONSIVE_DISPLAY_AD',
    UNIVERSAL_APP_AD = 'UNIVERSAL_APP_AD',
    UNKNOW = 'UNKNOW',
  }
}
