export enum AdGroupType {
  UNKNOWN = 'UNKNOWN',
  SEARCH_STANDARD = 'SEARCH_STANDARD',
  SEARCH_DYNAMIC_ADS = 'SEARCH_DYNAMIC_ADS',
  DISPLAY_STANDARD = 'DISPLAY_STANDARD',
  SHOPPING_PRODUCT_ADS = 'SHOPPING_PRODUCT_ADS',
  SHOPPING_SHOWCASE_ADS = 'SHOPPING_SHOWCASE_ADS',
  SHOPPING_GOAL_OPTIMIZED_ADS = 'SHOPPING_GOAL_OPTIMIZED_ADS',
}
