export enum CriterionTypeGroup {
  KEYWORD = 'KEYWORD',
  USER_INTEREST_AND_LIST = 'USER_INTEREST_AND_LIST',
  VERTICAL = 'VERTICAL',
  GENDER = 'GENDER',
  AGE_RANGE = 'AGE_RANGE',
  PLACEMENT = 'PLACEMENT',
  PARENT = 'PARENT',
  INCOME_RANGE = 'INCOME_RANGE',
  NONE = 'NONE',
  UNKNOWN = 'UNKNOWN',
}
