export enum AdServingOptimizationStatus {
  OPTIMIZE = 'OPTIMIZE',
  CONVERSION_OPTIMIZE = 'CONVERSION_OPTIMIZE',
  ROTATE = 'ROTATE',
  ROTATE_INDEFINITELY = 'ROTATE_INDEFINITELY',
  UNAVAILABLE = 'UNAVAILABLE',
  UNKNOWN = 'UNKNOWN',
}
