export enum AdvertisingChannelSubType {
  UNKNOWN = 'UNKNOWN',
  SEARCH_MOBILE_APP = 'SEARCH_MOBILE_APP',
  DISPLAY_MOBILE_APP = 'DISPLAY_MOBILE_APP',
  SEARCH_EXPRESS = 'SEARCH_EXPRESS',
  DISPLAY_EXPRESS = 'DISPLAY_EXPRESS',
  UNIVERSAL_APP_CAMPAIGN = 'UNIVERSAL_APP_CAMPAIGN',
  DISPLAY_SMART_CAMPAIGN = 'DISPLAY_SMART_CAMPAIGN',
  SHOPPING_GOAL_OPTIMIZED_ADS = 'SHOPPING_GOAL_OPTIMIZED_ADS',
  DISPLAY_GMAIL_AD = 'DISPLAY_GMAIL_AD'
}
