enum BidSource {
  ADGROUP = 'ADGROUP',
  CRITERION = 'CRITERION',
  ADGROUP_BIDDING_STRATEGY = 'ADGROUP_BIDDING_STRATEGY',
  CAMPAIGN_BIDDING_STRATEGY = 'CAMPAIGN_BIDDING_STRATEGY',
}

export { BidSource };
